import os
import re
import html2text
from reddit_poster import RedditPoster
from content_scraper import get_latest_post

REDDIT_API_CLIENT = os.environ['REDDIT_API_CLIENT']
REDDIT_API_SECRET = os.environ['REDDIT_API_SECRET']
REDDIT_USER = os.environ['REDDIT_USER']
REDDIT_PASSWORD = os.environ['REDDIT_PASSWORD']

# real
# NEWS_FLAIR = "4b9a56d8-550e-11ea-9b5f-0eb649837073"
# fake
NEWS_FLAIR = "049eb712-46fc-11ef-bc57-fee14a5d86b6"

# real
# SUBREDDIT_NAME = 'eq2'
# fake
SUBREDDIT_NAME = 'eq2apitesting'

ANNOUNCEMENTS_URL = "https://forums.everquest2.com/index.php?forums/announcements.11/"
UPDATE_NOTES_URL = "https://forums.everquest2.com/index.php?forums/update-notes.12/"
ROOT_URL = "https://forums.everquest2.com"


def main():
    reddit_poster = RedditPoster(REDDIT_API_CLIENT, REDDIT_API_SECRET, REDDIT_USER, REDDIT_PASSWORD, SUBREDDIT_NAME)

    sticky_class_name='structItemContainer-group structItemContainer-group--sticky'
    thread_list_class_name='structItemContainer-group js-threadList'
    announcement_title, announcement_latest_sticky_content, announcement_post_url = get_latest_post(ROOT_URL, ANNOUNCEMENTS_URL, sticky_class_name)
    update_notes_title, update_notes_latest_post_content, update_notes_post_url = get_latest_post(ROOT_URL, UPDATE_NOTES_URL, thread_list_class_name)

    announcement_markdown = __clean_and_convert_html_to_markdown(announcement_latest_sticky_content)
    update_notes_markdown = __clean_and_convert_html_to_markdown(update_notes_latest_post_content)

    announcement_markdown = __add_link_and_bot_tag(announcement_post_url, announcement_markdown)
    update_notes_markdown = __add_link_and_bot_tag(update_notes_post_url, update_notes_markdown)

    reddit_poster.submit(announcement_title, announcement_markdown, NEWS_FLAIR)
    reddit_poster.submit(update_notes_title, update_notes_markdown, NEWS_FLAIR)

def __add_link_and_bot_tag(post_url, markdown_content):
    link_markdown = f'[{post_url}]({post_url})\n\n'
    bot_tag = '\n\n This post was generated by u/eq2-bot - if there are any issues please message the moderators'
    return link_markdown + markdown_content + bot_tag


def __clean_and_convert_html_to_markdown(html_content):
    for div in html_content.find_all('div', class_='bbWrapper'):
        div.decompose()
    for img in html_content.find_all('img'):
        img.decompose()
    for a in html_content.find_all('a', class_='link link--external'):
        a.decompose()

    markdown_content = html2text.html2text(str(html_content))
    return __post_process_markdown(markdown_content)

def __post_process_markdown(markdown_content):
    # Remove Markdown image syntax
    markdown_content = re.sub(r'!\[.*?\]\(.*?\)', '', markdown_content)

    # Remove any remaining unwanted HTML tags
    markdown_content = re.sub(r'<[^>]+>', '', markdown_content)

    return markdown_content

if __name__ == "__main__":
    main()
